var teamData = (function () {

    var data = function () {

        var teamsGames = [

            {
                date: '10/28/2014',
                teamGuestName: 'Orlando',
                teamHostName: 'New Orleans',
                finalPointsGuest: 84,
                finalPointsHost: 101,
                fgMadeGuest:32,
                fgMadeHost:41,
                fgAttGuest:84,
                fgAttHost:101,
                threePointGuestHost: 4,
                threePointMadeHost: 4,
                threePointAttemptGuest: 11,
                threePointAttemptHost: 17,
                freeThrowsMadeGuest: 16,
                freeThrowsMadeHost: 15,
                freeThrowsAttemptGuest: 21,
                freeThrowsAttemptHost: 31,
                personalFoulsGuest: 25,
                personalFoulsHost: 17,
                steelsGuest: 25,
                steelsHost: 17,
                reboundsGuest: 56,
                reboundsHost: 62,
                assistsGuest: 17,
                assistsHost: 20,
                blocksGuest: 9,
                blocksHost: 17,
            },
            {
                date: '10/28/2014',
                teamGuestName: 'Dallas',
                teamHostName: 'San Antonio',
                finalPointsGuest: 100,
                finalPointsHost: 101,
                fgMadeGuest:38,
                fgMadeHost:37,
                fgAttGuest:78,
                fgAttHost:70,
                threePointGuestHost: 8,
                threePointMadeHost: 14,
                threePointAttemptGuest: 21,
                threePointAttemptHost: 28,
                freeThrowsMadeGuest: 16,
                freeThrowsMadeHost: 13,
                freeThrowsAttemptGuest: 19,
                freeThrowsAttemptHost: 16,
                personalFoulsGuest: 20,
                personalFoulsHost: 20,
                steelsGuest: 9,
                steelsHost: 5,
                reboundsGuest: 33,
                reboundsHost: 38,
                assistsGuest: 17,
                assistsHost: 23,
                blocksGuest: 3,
                blocksHost: 3,
            },
            {
                date: '10/28/2014',
                teamGuestName: 'Houston',
                teamHostName: 'LA Lakers',
                finalPointsGuest: 108,
                finalPointsHost: 90,
                fgMadeGuest:31,
                fgMadeHost:28,
                fgAttGuest:73,
                fgAttHost:79,
                threePointGuestHost: 13,
                threePointMadeHost: 3,
                threePointAttemptGuest: 29,
                threePointAttemptHost: 10,
                freeThrowsMadeGuest: 34,
                freeThrowsMadeHost: 31,
                freeThrowsAttemptGuest: 50,
                freeThrowsAttemptHost: 39,
                personalFoulsGuest: 30,
                personalFoulsHost: 32,
                steelsGuest: 7,
                steelsHost: 7,
                reboundsGuest: 47,
                reboundsHost: 36,
                assistsGuest: 22,
                assistsHost: 16,
                blocksGuest: 3,
                blocksHost: 3,
            },
            {
                date: '10/29/2014',
                teamGuestName: 'Milwaukee',
                teamHostName: 'Charlotte',
                finalPointsGuest: 106,
                finalPointsHost: 108,
                fgMadeGuest:39,
                fgMadeHost:41,
                fgAttGuest:80,
                fgAttHost:101,
                threePointGuestHost: 7,
                threePointMadeHost: 6,
                threePointAttemptGuest: 14,
                threePointAttemptHost: 21,
                freeThrowsMadeGuest: 21,
                freeThrowsMadeHost: 20,
                freeThrowsAttemptGuest: 24,
                freeThrowsAttemptHost: 29,
                personalFoulsGuest: 25,
                personalFoulsHost: 20,
                steelsGuest: 9,
                steelsHost: 8,
                reboundsGuest: 35,
                reboundsHost: 50,
                assistsGuest: 25,
                assistsHost: 27,
                blocksGuest: 10,
                blocksHost: 9,
            },
            {
                date: '10/29/2014',
                teamGuestName: 'Philadelphia',
                teamHostName: 'Indiana',
                finalPointsGuest: 91,
                finalPointsHost: 103,
                fgMadeGuest:34,
                fgMadeHost:38,
                fgAttGuest:89,
                fgAttHost:81,
                threePointGuestHost: 6,
                threePointMadeHost: 8,
                threePointAttemptGuest: 21,
                threePointAttemptHost: 25,
                freeThrowsMadeGuest: 17,
                freeThrowsMadeHost: 19,
                freeThrowsAttemptGuest: 30,
                freeThrowsAttemptHost: 28,
                personalFoulsGuest: 29,
                personalFoulsHost: 24,
                steelsGuest: 10,
                steelsHost: 5,
                reboundsGuest: 42,
                reboundsHost: 50,
                assistsGuest: 17,
                assistsHost: 22,
                blocksGuest: 5,
                blocksHost: 13,
            },
            {
                date: '10/29/2014',
                teamGuestName: 'Brooklyn',
                teamHostName: 'Boston',
                finalPointsGuest: 105,
                finalPointsHost: 121,
                fgMadeGuest:39,
                fgMadeHost:49,
                fgAttGuest:80,
                fgAttHost:88,
                threePointGuestHost: 7,
                threePointMadeHost: 8,
                threePointAttemptGuest: 19,
                threePointAttemptHost: 22,
                freeThrowsMadeGuest: 20,
                freeThrowsMadeHost: 15,
                freeThrowsAttemptGuest: 26,
                freeThrowsAttemptHost: 23,
                personalFoulsGuest: 21,
                personalFoulsHost: 25,
                steelsGuest: 6,
                steelsHost: 11,
                reboundsGuest: 39,
                reboundsHost: 35,
                assistsGuest: 20,
                assistsHost: 28,
                blocksGuest: 7,
                blocksHost: 5,
            },
            {
                date: '10/29/2014',
                teamGuestName: 'Washington',
                teamHostName: 'Miami',
                finalPointsGuest: 95,
                finalPointsHost: 107,
                fgMadeGuest:36,
                fgMadeHost:39,
                fgAttGuest:75,
                fgAttHost:81,
                threePointGuestHost: 6,
                threePointMadeHost: 9,
                threePointAttemptGuest: 19,
                threePointAttemptHost: 28,
                freeThrowsMadeGuest: 17,
                freeThrowsMadeHost: 20,
                freeThrowsAttemptGuest: 24,
                freeThrowsAttemptHost: 23,
                personalFoulsGuest: 20,
                personalFoulsHost: 17,
                steelsGuest: 7,
                steelsHost: 9,
                reboundsGuest: 36,
                reboundsHost: 44,
                assistsGuest: 20,
                assistsHost: 20,
                blocksGuest: 2,
                blocksHost: 3,
            },
            {
                date: '10/29/2014',
                teamGuestName: 'Atlanta',
                teamHostName: 'Toronto',
                finalPointsGuest: 102,
                finalPointsHost: 109,
                fgMadeGuest:40,
                fgMadeHost:37,
                fgAttGuest:80,
                fgAttHost:90,
                threePointGuestHost: 13,
                threePointMadeHost: 8,
                threePointAttemptGuest: 22,
                threePointAttemptHost: 26,
                freeThrowsMadeGuest: 9,
                freeThrowsMadeHost: 27,
                freeThrowsAttemptGuest: 17,
                freeThrowsAttemptHost: 33,
                personalFoulsGuest: 24,
                personalFoulsHost: 22,
                steelsGuest: 6,
                steelsHost: 13,
                reboundsGuest: 42,
                reboundsHost: 48,
                assistsGuest: 26,
                assistsHost: 26,
                blocksGuest: 8,
                blocksHost: 9,
            },
            {
                date: '10/29/2014',
                teamGuestName: 'Minnesota',
                teamHostName: 'Memphis',
                finalPointsGuest: 101,
                finalPointsHost: 105,
                fgMadeGuest:39,
                fgMadeHost:43,
                fgAttGuest:86,
                fgAttHost:82,
                threePointGuestHost: 6,
                threePointMadeHost: 4,
                threePointAttemptGuest: 12,
                threePointAttemptHost: 15,
                freeThrowsMadeGuest: 17,
                freeThrowsMadeHost: 15,
                freeThrowsAttemptGuest: 23,
                freeThrowsAttemptHost: 20,
                personalFoulsGuest: 21,
                personalFoulsHost: 21,
                steelsGuest: 8,
                steelsHost: 10,
                reboundsGuest: 47,
                reboundsHost: 33,
                assistsGuest: 20,
                assistsHost: 21,
                blocksGuest: 4,
                blocksHost: 5,
            },
            {
                date: '10/29/2014',
                teamGuestName: 'Chicago',
                teamHostName: 'New York',
                finalPointsGuest: 104,
                finalPointsHost: 80,
                fgMadeGuest:36,
                fgMadeHost:31,
                fgAttGuest:24,
                fgAttHost:17,
                threePointGuestHost: 7,
                threePointMadeHost: 3,
                threePointAttemptGuest: 24,
                threePointAttemptHost: 17,
                freeThrowsMadeGuest: 25,
                freeThrowsMadeHost: 15,
                freeThrowsAttemptGuest: 30,
                freeThrowsAttemptHost: 17,
                personalFoulsGuest: 18,
                personalFoulsHost: 22,
                steelsGuest: 9,
                steelsHost: 9,
                reboundsGuest: 47,
                reboundsHost: 38,
                assistsGuest: 21,
                assistsHost: 19,
                blocksGuest: 4,
                blocksHost: 5,
            },
            {
                date: '04/18/2015',
                teamGuestName: 'Washington',
                teamHostName: 'Toronto',
                finalPointsGuest: 93,
                finalPointsHost: 86,
                fgMadeGuest:39,
                fgMadeHost:35,
                fgAttGuest:99,
                fgAttHost:92,
                threePointGuestHost: 6,
                threePointMadeHost: 6,
                threePointAttemptGuest: 21,
                threePointAttemptHost: 29,
                freeThrowsMadeGuest: 9,
                freeThrowsMadeHost: 10,
                freeThrowsAttemptGuest: 15,
                freeThrowsAttemptHost: 14,
                personalFoulsGuest: 18,
                personalFoulsHost: 21,
                steelsGuest: 6,
                steelsHost: 5,
                reboundsGuest: 61,
                reboundsHost: 48,
                assistsGuest: 22,
                assistsHost: 21,
                blocksGuest: 3,
                blocksHost: 4,
            },
            {
                date: '04/18/2015',
                teamGuestName: 'New Orleans',
                teamHostName: 'Golden State',
                finalPointsGuest: 99,
                finalPointsHost: 106,
                fgMadeGuest:35,
                fgMadeHost:37,
                fgAttGuest:83,
                fgAttHost:81,
                threePointGuestHost: 9,
                threePointMadeHost: 11,
                threePointAttemptGuest: 22,
                threePointAttemptHost: 29,
                freeThrowsMadeGuest: 20,
                freeThrowsMadeHost: 21,
                freeThrowsAttemptGuest: 25,
                freeThrowsAttemptHost: 34,
                personalFoulsGuest: 28,
                personalFoulsHost: 21,
                steelsGuest: 8,
                steelsHost: 11,
                reboundsGuest: 44,
                reboundsHost: 47,
                assistsGuest: 24,
                assistsHost: 24,
                blocksGuest: 5,
                blocksHost: 6,
            },
            {
                date: '04/18/2015',
                teamGuestName: 'Milwaukee',
                teamHostName: 'Chicago',
                finalPointsGuest: 91,
                finalPointsHost: 103,
                fgMadeGuest:35,
                fgMadeHost:38,
                fgAttGuest:89,
                fgAttHost:83,
                threePointGuestHost: 4,
                threePointMadeHost: 12,
                threePointAttemptGuest: 16,
                threePointAttemptHost: 32,
                freeThrowsMadeGuest: 17,
                freeThrowsMadeHost: 15,
                freeThrowsAttemptGuest: 26,
                freeThrowsAttemptHost: 22,
                personalFoulsGuest: 23,
                personalFoulsHost: 21,
                steelsGuest: 11,
                steelsHost: 8,
                reboundsGuest: 41,
                reboundsHost: 52,
                assistsGuest: 22,
                assistsHost: 30,
                blocksGuest: 3,
                blocksHost: 7,
            },
            {
                date: '04/18/2015',
                teamGuestName: 'Dallas',
                teamHostName: 'Houston',
                finalPointsGuest: 108,
                finalPointsHost: 118,
                fgMadeGuest:44,
                fgMadeHost:38,
                fgAttGuest:99,
                fgAttHost:85,
                threePointGuestHost: 6,
                threePointMadeHost: 10,
                threePointAttemptGuest: 17,
                threePointAttemptHost: 25,
                freeThrowsMadeGuest: 14,
                freeThrowsMadeHost: 32,
                freeThrowsAttemptGuest: 17,
                freeThrowsAttemptHost: 45,
                personalFoulsGuest: 28,
                personalFoulsHost: 22,
                steelsGuest: 5,
                steelsHost: 111,
                reboundsGuest: 49,
                reboundsHost: 44,
                assistsGuest: 19,
                assistsHost: 26,
                blocksGuest: 4,
                blocksHost: 9,
            },
            {
                date: '04/19/2015',
                teamGuestName: 'Boston',
                teamHostName: 'Cleveland',
                finalPointsGuest: 100,
                finalPointsHost: 113,
                fgMadeGuest:37,
                fgMadeHost:37,
                fgAttGuest:79,
                fgAttHost:82,
                threePointGuestHost: 8,
                threePointMadeHost: 13,
                threePointAttemptGuest: 22,
                threePointAttemptHost: 31,
                freeThrowsMadeGuest: 18,
                freeThrowsMadeHost: 26,
                freeThrowsAttemptGuest: 22,
                freeThrowsAttemptHost: 33,
                personalFoulsGuest: 29,
                personalFoulsHost: 23,
                steelsGuest: 7,
                steelsHost: 6,
                reboundsGuest: 34,
                reboundsHost: 46,
                assistsGuest: 24,
                assistsHost: 19,
                blocksGuest: 4,
                blocksHost: 5,
            },
            {
                date: '04/19/2015',
                teamGuestName: 'Brooklyn',
                teamHostName: 'Atlanta',
                finalPointsGuest: 92,
                finalPointsHost: 99,
                fgMadeGuest:36,
                fgMadeHost:34,
                fgAttGuest:79,
                fgAttHost:79,
                threePointGuestHost: 5,
                threePointMadeHost: 10,
                threePointAttemptGuest: 20,
                threePointAttemptHost: 30,
                freeThrowsMadeGuest: 15,
                freeThrowsMadeHost: 21,
                freeThrowsAttemptGuest: 22,
                freeThrowsAttemptHost: 22,
                personalFoulsGuest: 19,
                personalFoulsHost: 21,
                steelsGuest: 8,
                steelsHost: 11,
                reboundsGuest: 47,
                reboundsHost: 39,
                assistsGuest: 18,
                assistsHost: 19,
                blocksGuest: 0,
                blocksHost: 3,
            },
            {
                date: '04/19/2015',
                teamGuestName: 'Portland',
                teamHostName: 'Memphis',
                finalPointsGuest: 86,
                finalPointsHost: 100,
                fgMadeGuest:32,
                fgMadeHost:39,
                fgAttGuest:95,
                fgAttHost:88,
                threePointGuestHost: 8,
                threePointMadeHost: 3,
                threePointAttemptGuest: 26,
                threePointAttemptHost: 9,
                freeThrowsMadeGuest: 14,
                freeThrowsMadeHost: 19,
                freeThrowsAttemptGuest: 19,
                freeThrowsAttemptHost: 26,
                personalFoulsGuest: 23,
                personalFoulsHost: 18,
                steelsGuest: 5,
                steelsHost: 8,
                reboundsGuest: 56,
                reboundsHost: 48,
                assistsGuest: 18,
                assistsHost: 21,
                blocksGuest: 7,
                blocksHost: 9,
            },
            {
                date: '04/19/2015',
                teamGuestName: 'San Antonio',
                teamHostName: 'LA Clippers',
                finalPointsGuest: 92,
                finalPointsHost: 107,
                fgMadeGuest:34,
                fgMadeHost:40,
                fgAttGuest:93,
                fgAttHost:78,
                threePointGuestHost: 10,
                threePointMadeHost: 10,
                threePointAttemptGuest: 33,
                threePointAttemptHost: 18,
                freeThrowsMadeGuest: 14,
                freeThrowsMadeHost: 17,
                freeThrowsAttemptGuest: 26,
                freeThrowsAttemptHost: 28,
                personalFoulsGuest: 23,
                personalFoulsHost: 21,
                steelsGuest: 9,
                steelsHost: 9,
                reboundsGuest: 49,
                reboundsHost: 46,
                assistsGuest: 25,
                assistsHost: 16,
                blocksGuest: 3,
                blocksHost: 8,
            },
            {
                date: '04/20/2015',
                teamGuestName: 'Milwaukee',
                teamHostName: 'Chicago',
                finalPointsGuest: 82,
                finalPointsHost: 91,
                fgMadeGuest:32,
                fgMadeHost:31,
                fgAttGuest:90,
                fgAttHost:81,
                threePointGuestHost: 4,
                threePointMadeHost: 12,
                threePointAttemptGuest: 17,
                threePointAttemptHost: 33,
                freeThrowsMadeGuest: 14,
                freeThrowsMadeHost: 17,
                freeThrowsAttemptGuest: 17,
                freeThrowsAttemptHost: 27,
                personalFoulsGuest: 22,
                personalFoulsHost: 19,
                steelsGuest: 10,
                steelsHost: 2,
                reboundsGuest: 48,
                reboundsHost: 64,
                assistsGuest: 13,
                assistsHost: 26,
                blocksGuest: 9,
                blocksHost: 10,
            },
            {
                date: '04/20/2015',
                teamGuestName: 'New Orleans',
                teamHostName: 'Golden State',
                finalPointsGuest: 87,
                finalPointsHost: 97,
                fgMadeGuest:31,
                fgMadeHost:38,
                fgAttGuest:82,
                fgAttHost:86,
                threePointGuestHost: 7,
                threePointMadeHost: 9,
                threePointAttemptGuest: 20,
                threePointAttemptHost: 30,
                freeThrowsMadeGuest: 18,
                freeThrowsMadeHost: 12,
                freeThrowsAttemptGuest: 24,
                freeThrowsAttemptHost: 19,
                personalFoulsGuest: 20,
                personalFoulsHost: 18,
                steelsGuest: 10,
                steelsHost: 8,
                reboundsGuest: 42,
                reboundsHost: 49,
                assistsGuest: 21,
                assistsHost: 27,
                blocksGuest: 4,
                blocksHost: 6,
            },
            {
                date: '04/21/2015',
                teamGuestName: 'Boston',
                teamHostName: 'Cleveland',
                finalPointsGuest: 91,
                finalPointsHost: 99,
                fgMadeGuest:33,
                fgMadeHost:34,
                fgAttGuest:85,
                fgAttHost:76,
                threePointGuestHost: 6,
                threePointMadeHost: 7,
                threePointAttemptGuest: 22,
                threePointAttemptHost: 29,
                freeThrowsMadeGuest: 19,
                freeThrowsMadeHost: 24,
                freeThrowsAttemptGuest: 22,
                freeThrowsAttemptHost: 26,
                personalFoulsGuest: 22,
                personalFoulsHost: 22,
                steelsGuest: 6,
                steelsHost: 7,
                reboundsGuest: 39,
                reboundsHost: 47,
                assistsGuest: 19,
                assistsHost: 18,
                blocksGuest: 3,
                blocksHost: 10,
            },
            {
                date: '04/21/2015',
                teamGuestName: 'Washington',
                teamHostName: 'Toronto',
                finalPointsGuest: 117,
                finalPointsHost: 106,
                fgMadeGuest:42,
                fgMadeHost:39,
                fgAttGuest:79,
                fgAttHost:80,
                threePointGuestHost: 10,
                threePointMadeHost: 7,
                threePointAttemptGuest: 21,
                threePointAttemptHost: 18,
                freeThrowsMadeGuest: 23,
                freeThrowsMadeHost: 21,
                freeThrowsAttemptGuest: 34,
                freeThrowsAttemptHost: 32,
                personalFoulsGuest: 24,
                personalFoulsHost: 27,
                steelsGuest: 6,
                steelsHost: 8,
                reboundsGuest: 45,
                reboundsHost: 28,
                assistsGuest: 26,
                assistsHost: 19,
                blocksGuest: 6,
                blocksHost: 1,
            },
            {
                date: '04/21/2015',
                teamGuestName: 'Dallas',
                teamHostName: 'Houston',
                finalPointsGuest: 99,
                finalPointsHost: 111,
                fgMadeGuest:33,
                fgMadeHost:39,
                fgAttGuest:89,
                fgAttHost:88,
                threePointGuestHost: 6,
                threePointMadeHost: 6,
                threePointAttemptGuest: 22,
                threePointAttemptHost: 20,
                freeThrowsMadeGuest: 27,
                freeThrowsMadeHost: 27,
                freeThrowsAttemptGuest: 28,
                freeThrowsAttemptHost: 35,
                personalFoulsGuest: 23,
                personalFoulsHost: 23,
                steelsGuest: 4,
                steelsHost: 5,
                reboundsGuest: 46,
                reboundsHost: 49,
                assistsGuest: 14,
                assistsHost: 25,
                blocksGuest: 6,
                blocksHost: 5,
            },
            {
                date: '04/22/2015',
                teamGuestName: 'Brooklyn',
                teamHostName: 'Atlanta',
                finalPointsGuest: 91,
                finalPointsHost: 96,
                fgMadeGuest:35,
                fgMadeHost:35,
                fgAttGuest:78,
                fgAttHost:90,
                threePointGuestHost: 8,
                threePointMadeHost: 12,
                threePointAttemptGuest: 26,
                threePointAttemptHost: 31,
                freeThrowsMadeGuest: 13,
                freeThrowsMadeHost: 14,
                freeThrowsAttemptGuest: 18,
                freeThrowsAttemptHost: 19,
                personalFoulsGuest: 21,
                personalFoulsHost: 18,
                steelsGuest: 6,
                steelsHost: 11,
                reboundsGuest: 49,
                reboundsHost: 41,
                assistsGuest: 23,
                assistsHost: 27,
                blocksGuest: 5,
                blocksHost: 7,
            },
            {
                date: '04/22/2015',
                teamGuestName: 'Portland',
                teamHostName: 'Memphis',
                finalPointsGuest: 82,
                finalPointsHost: 97,
                fgMadeGuest:30,
                fgMadeHost:38,
                fgAttGuest:77,
                fgAttHost:89,
                threePointGuestHost: 6,
                threePointMadeHost: 8,
                threePointAttemptGuest: 20,
                threePointAttemptHost:16,
                freeThrowsMadeGuest: 16,
                freeThrowsMadeHost: 13,
                freeThrowsAttemptGuest: 18,
                freeThrowsAttemptHost: 14,
                personalFoulsGuest: 13,
                personalFoulsHost: 19,
                steelsGuest: 4,
                steelsHost: 9,
                reboundsGuest: 42,
                reboundsHost: 41,
                assistsGuest: 11,
                assistsHost: 19,
                blocksGuest: 8,
                blocksHost: 7,
            },
            {
                date: '04/22/2015',
                teamGuestName: 'San Antonio',
                teamHostName: 'LA Clippers',
                finalPointsGuest: 111,
                finalPointsHost: 107,
                fgMadeGuest:42,
                fgMadeHost:39,
                fgAttGuest:91,
                fgAttHost:92,
                threePointGuestHost: 8,
                threePointMadeHost: 9,
                threePointAttemptGuest: 25,
                threePointAttemptHost: 29,
                freeThrowsMadeGuest: 19,
                freeThrowsMadeHost: 20,
                freeThrowsAttemptGuest: 26,
                freeThrowsAttemptHost: 37,
                personalFoulsGuest: 31,
                personalFoulsHost: 20,
                steelsGuest: 8,
                steelsHost: 5,
                reboundsGuest: 48,
                reboundsHost: 55,
                assistsGuest: 26,
                assistsHost: 23,
                blocksGuest: 6,
                blocksHost: 6,
            },
            {
                date: '04/23/2015',
                teamGuestName: 'Cleveland',
                teamHostName: 'Boston',
                finalPointsGuest: 103,
                finalPointsHost: 95,
                fgMadeGuest:38,
                fgMadeHost:36,
                fgAttGuest:84,
                fgAttHost:82,
                threePointGuestHost: 12,
                threePointMadeHost: 5,
                threePointAttemptGuest: 29,
                threePointAttemptHost: 19,
                freeThrowsMadeGuest: 15,
                freeThrowsMadeHost: 18,
                freeThrowsAttemptGuest: 24,
                freeThrowsAttemptHost: 21,
                personalFoulsGuest: 18,
                personalFoulsHost: 23,
                steelsGuest: 9,
                steelsHost: 6,
                reboundsGuest: 45,
                reboundsHost: 45,
                assistsGuest: 17,
                assistsHost: 20,
                blocksGuest: 7,
                blocksHost: 5,
            },
            {
                date: '04/23/2015',
                teamGuestName: 'Chicago',
                teamHostName: 'Milwaukee',
                finalPointsGuest: 113,
                finalPointsHost: 106,
                fgMadeGuest:40,
                fgMadeHost:43,
                fgAttGuest:89,
                fgAttHost:102,
                threePointGuestHost: 14,
                threePointMadeHost: 6,
                threePointAttemptGuest: 33,
                threePointAttemptHost: 19,
                freeThrowsMadeGuest: 19,
                freeThrowsMadeHost: 14,
                freeThrowsAttemptGuest: 24,
                freeThrowsAttemptHost: 25,
                personalFoulsGuest: 20,
                personalFoulsHost: 20,
                steelsGuest: 11,
                steelsHost: 11,
                reboundsGuest: 50,
                reboundsHost: 50,
                assistsGuest: 25,
                assistsHost: 24,
                blocksGuest: 6,
                blocksHost: 7,
            },
            {
                date: '04/23/2015',
                teamGuestName: 'Golden State',
                teamHostName: 'New Orleans',
                finalPointsGuest: 123,
                finalPointsHost: 119,
                fgMadeGuest:42,
                fgMadeHost:46,
                fgAttGuest:104,
                fgAttHost:90,
                threePointGuestHost: 14,
                threePointMadeHost: 6,
                threePointAttemptGuest: 41,
                threePointAttemptHost: 21,
                freeThrowsMadeGuest: 25,
                freeThrowsMadeHost: 21,
                freeThrowsAttemptGuest: 30,
                freeThrowsAttemptHost: 26,
                personalFoulsGuest: 22,
                personalFoulsHost: 28,
                steelsGuest: 4,
                steelsHost: 7,
                reboundsGuest: 51,
                reboundsHost: 47,
                assistsGuest: 24,
                assistsHost: 25,
                blocksGuest: 6,
                blocksHost: 8,
            },
            

        ]

        return teamsGames;


    }

    return data;

})();




